### ISSUE TITLE
Possibilities of encipher and decipher function in multisig runestone transaction hex

### ISSUE THREAD

**Issue by Rezzecup** [me-foundation/runestone-lib#73]
I'm implementing Runestone Airdrop process based on multisig admin wallet.
I'm planning to use this module to analyze the valid runestone after broadcasting runestone transactions.
Wondering about possibilities about that.

**Comment by summraznboi** [comment]
This is a great library for enciphering/deciphering runestones, no additional dependencies required. However, if you want to validate the actual rune balances of outputs, that will require the indexer part of the code to be set up, which requires storage and rpc client implementations.
