### ISSUE TITLE
Handling Edge Cases

### ISSUE THREAD

**Issue by suatap-alt** [me-foundation/runestone-lib#77]
I've been playing around with runestone-lib, and I'm kinda stumped. How does it handle weird cases or conflicts when you're encoding and decoding Runestones? Especially in those messy transactions with a bunch of rune operations? Are there any gotchas I should watch out for when working with a boatload of runes?

**Comment by summraznboi** [comment]
In terms of edicts, you just process them in order specified, and if runes run out, it runs out. Etchings with premine are applied first, and open mints by definition only come from following transactions; both of these increment the allocatable amount into the outputs. Any leftover uses the runestone-specified default, or if not specified is put into the first non-OP_RETURN output.
